version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - devops_db_data:/var/lib/mysql

  spring:
    image: taharejeb97/backend-spring:latest
    restart: unless-stopped
    ports:
      - "8088:8090"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    depends_on:
      - db
  achat-frontend:
    image: taharejeb97/frontend-angular:latest
    build:
      context: ./front/Dockerfile
      dockerfile: Dockerfile
    restart: unless-stopped

    ports:
      - "4200:4200"
    tty: true
volumes:
  devops_db_data:
